Writable:
  LogLevel: INFO
  Telemetry:
    Interval: "30s"

Service:
  Host: localhost
  Port: 59782  # Different port for HTTP version
  StartupMsg: "Ready-to-Use App Service (HTTP) with Prebuilt Functions"

# Disable MessageBus for HTTP-only testing
MessageBus:
  Disabled: true
  Optional:
    ClientId: app-service-ready-http
    
# Use HTTP trigger for testing
Trigger:
  Type: http

# Application-specific settings
ApplicationSettings:
  DeviceNames: "Random-Boolean-Device, Random-Float-Device, Random-Integer-Device"
