Writable:
  LogLevel: INFO
  Telemetry:
    Interval: ""

Service:
  Host: localhost
  Port: 59780 # Adjust if running multiple examples at the same time to avoid duplicate port conflicts
  StartupMsg: "This is a sample Filter/XML Transform Application Service"

MessageBus:
  Disabled: true  # Set to true if not using edgex-messagebus Trigger below and don't want Metrics
  Optional:
    ClientId: app-simple-filter-xml

Trigger:
  Type: http

# App Service specific simple settings
# Great for single string settings. For more complex structured custom configuration
# See https://docs.edgexfoundry.org/latest/microservices/application/AdvancedTopics/#custom-configuration
ApplicationSettings:
  DeviceNames: "Random-Float-Device, Random-Integer-Device"