Writable:
  LogLevel: "INFO"
  InsecureSecrets:
    redisdb:
      SecretName: redisdb
      SecretData:
        username: ''
        password: ''
    secure-messagebus:
      SecretName: secure-messagebus
      SecretData:
        username: ''
        password: ''

Registry:
  Host: localhost
  Port: 8500
  Type: consul

Database:
  Type: redis
  Host: localhost
  Port: 6379
  Timeout: 5000

MessageBus:
  Protocol: redis
  Host: localhost
  Port: 6379
  Type: redis
  AuthMode: none
  SecretName: secure-messagebus
  Optional:
    ClientId: app-service-virtual-devices-http
    SkipCertVerify: true

Service:
  Host: localhost
  Port: 59788
  ServerBindAddr: ""
  RequestTimeout: 5000
  HealthCheckInterval: 10s
  RequestReadTimeout: 5s
  RequestWriteTimeout: 5s
  MaxRequestSize: 0
  EnableCORS: false

ExternalMQTT:
  Enabled: false

Trigger:
  Type: "http"

# Device filter configuration
DeviceNames: 
  - "Random-Boolean-Device"
  - "Random-Float-Device"
  - "Random-Integer-Device"
  - "LabDoorSensor"
  - "LabCamera"
  - "LabSmokeSensor"
  - "LabFallSensor"

ApplicationSettings:
  ResourceNames: "Temperature,Humidity,Light,Motion,Sound,Camera"
  DeviceNames: "Random-Boolean-Device,Random-Float-Device,Random-Integer-Device"
  Simulate: false
